pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'mvn clean install'
        sh 'java -cp target/hello-world-1.0-SNAPSHOT.jar HelloWorld'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
        sh 'npm install'
        sh 'npm run lint'
        sh 'npm test'
        sh 'npm run build'
      }
    }
  }
}
